version: "3.3"

services:
  fsb:
    build: .
    restart: unless-stopped
    container_name: fsb
    environment:
      # required
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BIN_CHANNEL=${BIN_CHANNEL}
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - $HOME/TG-FileStreamBot:/app/.env
